### ISSUE TITLE
Theme colours don't activate in iTerm 2.1.4

### ISSUE THREAD

**Issue by henrebotha** [mhartington/oceanic-next-iterm#1]
The file imports (as in it shows up under the "load presets" dropdown), but selecting it doesn't actually make the colour pickers or the terminal itself change colours. The gif below was recorded on iTerm 2.1.1 but the behaviour is still exactly the same.

https://gyazo.com/ab22b100d3d21a6a61d7a92ac28d85e4

**Comment by henrebotha** [comment]
I played around with it quickly. It seems that some of the keys referenced, like `Link Color` or `Tab Color`, might be the problem - I removed every key in your scheme that does not also appear in [this scheme file](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/schemes/OceanicMaterial.itermcolors) and suddenly it works.

**Comment by derykfoote** [comment]
@henrebotha After making those changes, does the theme still look as intended? If so, would you mind sharing the updated .itermcolors file? Would love to get this up and running on iTerm 2.1.4!

**Comment by henrebotha** [comment]
I don't know if it still looks as intended. I'm sure the other keys that were in there were important somehow, I just don't know how. I _think_ it looks as intended. I know virtually nothing about terminal colours and that sort of thing.

Having said all of that, [here is my current .itermcolors file](https://gist.github.com/henrebotha/6bfe455e344793787853).

**Comment by derykfoote** [comment]
Thanks very much for sharing!

**Comment by mhartington** [comment]
Thanks for following up on this @henrebotha.
I'll go through and update the theme to fix the issues

**Comment by mhartington** [comment]
Just updated with 5d76836c03d5056bc6182fc4188f694167080d66

**Comment by henrebotha** [comment]
Thanks for the heads up! I'll check it out tomorrow.

**Comment by henrebotha** [comment]
Nice, it works perfectly. Why the change in colours? I notice the background is a little darker...

**Comment by mhartington** [comment]
This was to match the original a bit better.

https://github.com/mhartington/oceanic-next/issues/7#issuecomment-155116003

![](https://raw.githubusercontent.com/voronianski/oceanic-next-theme/master/screenshots/extended-class.png)

![screen shot 2015-11-09 at 11 28 29 am](https://cloud.githubusercontent.com/assets/2835826/11039311/0daa7436-86d5-11e5-8c40-8a635d9bb092.png)
