### ISSUE TITLE
colors not correct on iterm nightly build

### ISSUE THREAD

**Issue by leonidez** [mhartington/oceanic-next-iterm#2]
Hi, this is what my terminal looks like after downloading the latest iterm nightly build and the current Oceanic-Dark.itermcolors file:

<img width="1280" alt="screen shot 2016-01-25 at 6 48 16 pm" src="https://cloud.githubusercontent.com/assets/5011482/12569415/4f282d26-c394-11e5-993b-e28b992a6626.png">

I have made sure that my terminal is reporting `xterm-256color`. Is there anything else I need to do to get the colors to render correctly?

**Comment by mhartington** [comment]
Could you post the environment info?
Also, is that tmux? Which version

**Comment by leonidez** [comment]
@mhartington Here is my env:

<img width="1280" alt="screen shot 2016-01-25 at 8 38 43 pm" src="https://cloud.githubusercontent.com/assets/5011482/12571156/d36a20da-c3a3-11e5-8d47-32bc7ce4e129.png">

I am using tmux v 2.0. However, I should note that the terminal colors are the same both in and out of tmux.

**Comment by leonidez** [comment]
Also, I use zsh, which is currently up to date with master.

**Comment by mhartington** [comment]
Ah how, it seems it's caused by oh-my-zsh. Using the default theme seems to cause the issue.

<img width="1448" alt="screen shot 2016-01-25 at 8 22 49 pm" src="https://cloud.githubusercontent.com/assets/2835826/12571758/99ad0922-c3a1-11e5-93b4-e8f20c7db60b.png">

**Comment by leonidez** [comment]
Do you suggest I fix this by using https://github.com/mhartington/oceanic-next-shell ?

**Comment by mhartington** [comment]
Hm, no, that was a from an older project. Trying it out, it doesn't seem to fix anything.

It doesn't seem too off, and I'm not too versed with oh-my-zsh, so I'm fine with leaving this as it is. The only major change it that dirs are now teal instead of blue. Still looks good in my book :+1:
