### ISSUE TITLE
Doesn't work in iTerm2 2.1.4

### ISSUE THREAD

**Issue by olalonde** [mhartington/oceanic-next-iterm#3]
I tried importing the scheme and while it shows in the presets list, selecting it doesn't change any color. :/

**Comment by olalonde** [comment]
This seems to work though: https://gist.github.com/henrebotha/6bfe455e344793787853

**Comment by mhartington** [comment]
Fixed. Had some local changes for iterm3 beta that I accidentally committed

**Comment by olalonde** [comment]
Thanks, works.
